const actions = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_CART: "FETCH_CART",
    ADD_TO_CART: "ADD_TO_CART",
    UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    EMPTY_CART: "EMPTY_CART",
    REFRESH_CART: "REFRESH_CART",
    GENERATE_CHECKOUT_TOKEN: "GENERATE_CHECKOUT_TOKEN",
    FETCH_SHIPPING_COUNTRIES: "FETCH_SHIPPING_COUNTRIES",
    SET_SHIPPING_COUNTRY: "SET_SHIPPING_COUNTRY",
    FETCH_SHIPPING_SUBDIVISIONS: "FETCH_SHIPPING_SUBDIVISIONS",
    SET_SHIPPING_SUBDIVISION: "SET_SHIPPING_SUBDIVISION",
    FETCH_SHIPPING_OPTIONS: "FETCH_SHIPPING_OPTIONS",
    SET_SHIPPING_OPTION: "SET_SHIPPING_OPTION",
    SET_SHIPPING_DATA: "SET_SHIPPING_DATA",
    CAPTURE_CHECKOUT: "CAPTURE_CHECKOUT",
    SET_ERROR: "SET_ERROR",
};

export default actions;
